version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432

  api:
    build: .
    command: uvicorn main:api --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - postgres
